# Team Microsoft

## 1: Import packages

In [149]:
import pandas as pd 
import seaborn as sns
import numpy as np
import re
import string
import sklearn
import csv,json

import matplotlib.pyplot as plt
from matplotlib import collections  as mc
%matplotlib inline

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.base import TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV
from sklearn.model_selection import train_test_split

import spacy
from spacy.lang.en.stop_words import STOP_WORDS as stpw

#sns.set_style("white")
#%load_ext autoreload
#%autoreload 2
#from sklearn import datasets


#%load_ext autoreload
#%autoreload 2

In [150]:
df = pd.read_csv("https://raw.githubusercontent.com/KVVisDon/Data-Mining-Project/main/data/training_data.csv")


df_test = pd.read_csv("https://raw.githubusercontent.com/KVVisDon/Data-Mining-Project/main/data/test_data.csv")

df

id  ... target
0      3738  ...      0
1       853  ...      0
2     10540  ...      1
3      5988  ...      1
4      6328  ...      1
...     ...  ...    ...
6466   4377  ...      1
6467   3408  ...      0
6468   9794  ...      1
6469  10344  ...      1
6470   1779  ...      1

[6471 rows x 5 columns]

## 1.2: Base rate

In [151]:
br = df.target.value_counts().max()/df.target.value_counts().sum()
number_per_class = df.target.value_counts()
print(number_per_class)
print("Base rate is",str(round(br,2)))

0    3701
1    2770
Name: target, dtype: int64
Base rate is 0.57


# 2: Cleaning
###Basic : first we defined a tokenzation function, and removed duplicates based on subset ['text','keyword']

In [152]:
### Notes: If you look at the table up, you can see that there are many NaN locations, maybe we should do something about it? - location pas incluse dans le modèle
### I believe that our submission might not have worked because of the duplicate removal
### Our accuracy could be better also if we replace %20 by a space, maybe the keywords are badly encoded!
### Is it normal that "mytokens = word" appears twice in the remove hashtags, @ section?

In [153]:
sp = spacy.load('en_core_web_sm')
punctuations = string.punctuation
stop_words = spacy.lang.en.stop_words.STOP_WORDS

def spacy_token(message):
    
  mytokens = sp(message)
  # Lemmatize each token and convert each token into lowercase
  mytokens = [ word.lemma_.lower().strip() if word.lemma_ != "-PRON-" else word.lower_ for word in mytokens ]

  # Remove stop words and punctuation
  mytokens = [ word for word in mytokens if word not in stop_words and word not in punctuations ]

  # Remove hashtags, @
  mytokens = [ word.replace('@','').replace('#', '') for word in mytokens ]

  mytokens = [ word.replace('rt @', '').replace('rt', '') for word in mytokens ]
      
  mytokens = [ word for word in mytokens if word not in [""] ]

  return mytokens

def preprocess(dataframe):
  # Pre-processing text, of dataframe
  # for each row in dataframe: 
  #   get 'text' value (tweets), clean it (lemmatize - lowercase - remove stop words + punctuations), set cleaned 'text' value
  #   get 'keyword' value, replace the '%20' with <space>

  for index in dataframe.index:

    # Get TEXT value
    text_to_clean = str(dataframe.at[index,'text'])

    # Remove hyperlink (http:/t.co.....)
    text_to_clean = re.sub(r"http\S+", "", text_to_clean)

    text_to_clean = re.sub(r"‰\S+", "", text_to_clean)

    # Build cleaned TEXT
    text_cleaned = ''.join(text_to_clean)

    #--------------------------------------------------

    # Cleaned TEXT into dataframe
    dataframe.at[index,'text'] = text_cleaned

    # Get 'KEYWORD' value
    keyword_to_clean = str(dataframe.at[index,'keyword'])

    # Remove '%20'
    keyword_cleaned = keyword_to_clean.replace("%20"," ")

    # Cleaned KEYWORD into dataframe
    dataframe.at[index,'keyword'] = keyword_cleaned

  return dataframe

#df = df.drop(columns=['id'])

df = preprocess(df)

df





id  ... target
0      3738  ...      0
1       853  ...      0
2     10540  ...      1
3      5988  ...      1
4      6328  ...      1
...     ...  ...    ...
6466   4377  ...      1
6467   3408  ...      0
6468   9794  ...      1
6469  10344  ...      1
6470   1779  ...      1

[6471 rows x 5 columns]

# 3: Train a model
###Basic : 
- split train/test (80/20)
- define TF-IDF vectorizer
- define classifier
- fit model on training set
- first evaluation

In [154]:
X = df['text']
y = df['target']

# Train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=59)

X_train

# Define vectorizer
tfidf = TfidfVectorizer(sublinear_tf=True, min_df=5, norm='l2', encoding='latin-1', ngram_range=(1, 2), tokenizer=spacy_token)

# Define classifier
classifier = LogisticRegression(solver='lbfgs', max_iter=1000, random_state=59)

# Create pipeline
pipe = Pipeline([('vectorizer', tfidf),
                ('classifier', classifier)])


[['Black Eye 9: A space battle occurred at Star O784 involving 3 fleets totaling 3945 ships with 17 destroyed', 'destroyed'], ['#world FedEx no longer to transport bioterror germs in wake of anthrax lab mishaps  ', 'bioterror'], ['Reality Training: Train falls off elevated tracks during windstorm  #Paramedic #EMS', 'windstorm'], ['#Taiwan Grace: expect that large rocks trees mud unstable and/or saturated land may slide ..very hazardous in hilly/mountain areas...', 'hazardous'], ['New ISIS Video: ISIS Threatens to Behead Croatian Hostage Within 48 Hours - TLVFaces - TLVFaces#auspol ', 'hostage'], ["FreeBesieged: .MartinMJ22 YouGov Which '#Tory landslide' ... you can't POSSIBLY mean the wafer-thin majority of #G ", 'landslide'], ['Billionaires have a plan to free half a billion dollars trapped in Venezuela for two years @BlakeSchmidt reports.\n\n', 'trapped'], ['@JamesMelville Some old testimony of weapons used to promote conflicts\nTactics - corruption &amp; infiltration of groups\n', '

In [155]:
# Fit model on training set
pipe.fit(X_train, y_train)

nFeat = 0
for i in tfidf.get_feature_names():
  nFeat += 1
print("number of features created by the TF-IDF vector :",str(nFeat))

y_pred = pipe.predict(X_test)

#first evaluation
print(f"ACCURACY SCORE test:\n{accuracy_score(y_test, y_pred):.3f}")

print(f"ACCURACY SCORE train:\n{accuracy_score(y_train, pipe.predict(X_train)):.3f}")

print(f"CONFUSION MATRIX:\n{confusion_matrix(y_test, y_pred)}")

number of features created by the TF-IDF vector : 2286
ACCURACY SCORE test:
0.788
ACCURACY SCORE train:
0.859
CONFUSION MATRIX:
[[644  99]
 [175 377]]


# 4: First submission
###Basic : 
- mount the drive in order to save the csv with submission values
- split train/test (80/20)
- define TF-IDF vectorizer
- define classifier
- fit model on training set

In [156]:
#Mount a google drive
from google.colab import drive

drive.mount('drive')


#To improve performance : drop unused columns ('id' for now)
test_data = df_test['text']


# Get & print the number of features generated by the TF-IDF vector
nFeat = 0
for i in tfidf.get_feature_names():
  nFeat += 1
print("number of features created by the TF-IDF vector :",str(nFeat))

test_pred = pipe.predict(test_data)
print(type(test_pred))
print(test_pred)

#first evaluation
print(f"ACCURACY SCORE test:\n{accuracy_score(y_test, y_pred):.3f}")

print(f"ACCURACY SCORE train:\n{accuracy_score(y_train, pipe.predict(X_train)):.3f}")

print(f"CONFUSION MATRIX:\n{confusion_matrix(y_test, y_pred)}")

Mounted at drive
number of features created by the TF-IDF vector : 2286
<class 'numpy.ndarray'>
[0 0 1 ... 1 0 1]
ACCURACY SCORE test:
0.788
ACCURACY SCORE train:
0.859
CONFUSION MATRIX:
[[644  99]
 [175 377]]


In [ ]:
#### We should try to create an index, like add the timestamp to the file name so we can run this and not overwrite the previous submissions
### OR we can also name the file: submission-[ACCURACYSCORE].csv

In [157]:
#Handle the submission file
submission_file = pd.DataFrame(test_pred,columns=['target'])

submission_file.to_csv('submission_one.csv', index=False)

!cp submission_one.csv "drive/My Drive/Team_Microsoft"